### PR TITLE
Adjust colorscheme and add custom logo

### PR DESCRIPTION
**Pull request by weilbith**
Roy has adapted the default color scheme with my help. Also the logo has been exchanged in favor for a trustlines one.

### CODE REVIEW

**Comment by schmir-at-bb** [comment]
@berndbohmeier Can you take care of this while you're working on the blockscout?

**Comment by weilbith** [comment]
@berndbohmeier you are completely right, this makes much more sense and merge the upstreams becomes not a nightmare. 
Where do you define the environment variables like `NETWORK`, `LOGO`, `COIN` etc. pp.? I thought there must be a `.env` like variable at root.

**Comment by berndbohmeier** [comment]
They are just defined on the server. I would just document it somewhere.

**Comment by weilbith** [comment]
Okay, the colors will be already applied by this. Only the logo is left to become applied.

**Pull request merged**
