### PR TITLE
Change font to local Inter

### PR DESCRIPTION
**Pull request by Smokyish**
## Motivation

*We should merge this because i) we can't use Google Fonts and ii) because the currently used font is outdated.*

### Enhancements
*Adds local versions of the Inter font set and sets Inter as the font used.*

### CODE REVIEW

**Comment by Smokyish** [comment]
@weilbith Please test locally and review.

**Comment by weilbith** [comment]
@Smokyish I was able to fix the font loading. Since I have no write permission on your work I pushed the updated branch to my own one. Checkout commit `cfd85d55ea2f99cb48a643ad16bc80f759a9e3fe` and cherry-pick it to your own repo and push it. 

Here are screenshots how this looks with the new font on my host (with Firefox). Note that I did not connect a node to and have not database so there is no chain data displayed. I hope it is still enough to inspect. The second image shows that the correct font get loaded.

screenshot_1587546835
screenshot_1587546929

**Comment by Smokyish** [comment]
@weilbith Thanks, have added your commit to the PR!

**Comment by weilbith** [comment]
@Smokyish I know this is fuzzy but can you confirm via the screenshots that the font looks correct? I can give you also a video chat demo with zoom if you prefer. :shrug: 
Then I'll merge.

**Comment by Smokyish** [comment]
@weilbith Yes, looks correct 👍

**Pull request merged**
